apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: LoadBalancer # em cloud aqui seria gerado um IP externo
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
