version: '3'

services:

  app:
    build:
      context: ./node
    image: node-plus
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on:
      - db
    entrypoint: wait-for db:3306 -t 40 -- docker-entrypoint.sh

  db:
    image: mysql:8.2.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_USER=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge